## ASHRAE 140-2023

Section 7: CASE 940 - Hign  Mass, Thermostat setback

_opensimula: v0.5_

In [1]:
import opensimula as osm

sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_json("cases/case_940.json")

Reading project data from dictonary
Reading completed.
Checking project: Case 940
Checking completed.

In [2]:
pro.show_3D()

In [3]:
pro.simulate()

Calculating solar direct shadows ...
Simulating Case 940: ...

100%|██████████| 8760/8760 [00:18<00:00, 482.11step/s, n_iter=2]

In [4]:
import pandas as pd
import numpy as np

# Heating and Cooling Loads
load = pro.component("spaces_1").variable("system_sensible_heat").values
annual_heating = np.where(load>0,load,0).sum()/1e6
annual_cooling = np.where(load<0,-load,0).sum()/1e6
peak_heating = load.max()/1000
i_peak_heating = np.argmax(load)
peak_cooling = -load.min()/1000
i_peak_cooling = np.argmin(load)

excel = pd.DataFrame()
excel["Annual_heating"] = [annual_heating]
excel["Annual_cooling"] = [annual_cooling]
excel["Peak_heating"] = [peak_heating]
excel["Heating_month"] = [pro.dates()[i_peak_heating].strftime("%b")]
excel["Heating_day"] = [pro.dates()[i_peak_heating].strftime("%d")]
excel["Heating_hour"] = [int(pro.dates()[i_peak_heating].strftime("%H"))+1]
excel["Peak_cooling"] = [peak_cooling]
excel["Cooling_month"] = [pro.dates()[i_peak_cooling].strftime("%b")]
excel["Cooling_day"] = [pro.dates()[i_peak_cooling].strftime("%d")]
excel["Cooling_hour"] = [int(pro.dates()[i_peak_cooling].strftime("%H"))+1]
excel.to_clipboard()
excel

,Annual_heating,Annual_cooling,Peak_heating,Heating_month,Heating_day,Heating_hour,Peak_cooling,Cooling_month,Cooling_day,Cooling_hour
0,1.13014,2.526095,3.273709,Dec,31,9,2.845726,Oct,01,14

In [5]:
# 1-FEB
day_df= pd.DataFrame()
intervalo = ["2001-02-01","2001-02-02"]
aux =  pro.component("spaces_1").variable_dataframe(interval=intervalo)
day_df["T (ºC)"] = aux["temperature"]
aux =  pro.component("system").variable_dataframe(interval=intervalo)
day_df["Load (kWh)"] = aux["Q_sensible"]/1000
day_df.to_clipboard()
day_df

        T (ºC)  Load (kWh)
744  15.414540    0.000000
745  14.779699    0.000000
746  14.184079    0.000000
747  13.592290    0.000000
748  13.125434    0.000000
749  12.582279    0.000000
750  12.130376    0.000000
751  15.000000    0.871178
752  20.000000    1.926983
753  20.000000    0.955175
754  20.000000    0.179181
755  21.473393    0.000000
756  23.399072    0.000000
757  24.466555    0.000000
758  25.227499    0.000000
759  25.245612    0.000000
760  24.367313    0.000000
761  22.431239    0.000000
762  21.310712    0.000000
763  20.406575    0.000000
764  20.000000    0.165042
765  20.000000    0.436727
766  20.000000    0.635870
767  17.746037    0.000000