## EDIFICIO CURSO ATECYR HULC

Edificio importado desde HULC, es el edificio que usamos como pequeño terciario en los CURSOS de ATECYR.

In [13]:
import opensimula as osm

sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_json("edificio_curso_hulc.json")

Reading project data from file: edificio_curso_hulc.json
Reading completed.
Checking project: Edificio_curso_hulc
Checking completed.

In [15]:
import datetime as dt

date = dt.datetime(2001,3,21,19,0,0)
#pro.show_3D(jupyter=True)
pro.show_3D_shadows(date,jupyter=True)
#pro.show_3D_shadows_animation(date,jupyter=True)

In [ ]:
pro.parameter("shadow_calculation").value= "INTERPOLATION"
pro.simulate()
# 30s calculando las sombras de directa
# 4m:55s Simulando con shadow_calculation = INSTANT, n_iter = 4
# 1m:21s Simulando con shadow_calculation = INTERPOLATION, n_iter = 4

Calculating solar direct shadows ...
Simulating Edificio_curso_hulc: ...

100%|██████████| 8760/8760 [01:21<00:00, 107.36step/s, n_iter=4]

In [12]:
pro